name: Add issues to roadmap project

on:
  issues:
    types:
      - labeled

jobs:
  add-issue-to-roadmap-project:
    name: Add issue to roadmap project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/users/DmitriyLewen/projects/1
          github-token: ${{ secrets.ADD_TO_ROADMAP }}
          labeled: priority/backlog
        id: add-project
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/users/DmitriyLewen/projects/1
          github-token: ${{ secrets.ADD_TO_ROADMAP }}
          labeled: priority/important-longterm, priority/important-soon, priority/critical-urgent
          label-operator: OR
        id: add-project
      - uses: titoportas/update-project-fields@v0.1.0
        with:
          project-url: https://github.com/users/DmitriyLewen/projects/1
          github-token: ${{ secrets.ADD_TO_ROADMAP }}
          item-id: ${{ steps.add-project.outputs.itemId }} # Use the item-id output of the previous step
          field-keys: Status
          field-values: Done